# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wizard-interface.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(966, 1168)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 966, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuOpen = QtGui.QMenu(self.menubar)
        self.menuOpen.setObjectName(_fromUtf8("menuOpen"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.dockWidget = QtGui.QDockWidget(MainWindow)
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout_3 = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.dockWidget.setWidget(self.dockWidgetContents)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(4), self.dockWidget)
        self.dockWidget_3 = QtGui.QDockWidget(MainWindow)
        self.dockWidget_3.setObjectName(_fromUtf8("dockWidget_3"))
        self.dockWidgetContents_8 = QtGui.QWidget()
        self.dockWidgetContents_8.setObjectName(_fromUtf8("dockWidgetContents_8"))
        self.gridLayout_2 = QtGui.QGridLayout(self.dockWidgetContents_8)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.frame_3 = QtGui.QFrame(self.dockWidgetContents_8)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 200))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayoutWidget = QtGui.QWidget(self.frame_3)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 711, 194))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.coverButton1 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.coverButton1.setObjectName(_fromUtf8("coverButton1"))
        self.verticalLayout.addWidget(self.coverButton1)
        self.coverButton2 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.coverButton2.setObjectName(_fromUtf8("coverButton2"))
        self.verticalLayout.addWidget(self.coverButton2)
        self.coverButton3 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.coverButton3.setObjectName(_fromUtf8("coverButton3"))
        self.verticalLayout.addWidget(self.coverButton3)
        self.coverButton4 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.coverButton4.setObjectName(_fromUtf8("coverButton4"))
        self.verticalLayout.addWidget(self.coverButton4)
        self.coverButton5 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.coverButton5.setObjectName(_fromUtf8("coverButton5"))
        self.verticalLayout.addWidget(self.coverButton5)
        self.coverButton6 = QtGui.QPushButton(self.verticalLayoutWidget)
        self.coverButton6.setObjectName(_fromUtf8("coverButton6"))
        self.verticalLayout.addWidget(self.coverButton6)
        self.gridLayout_2.addWidget(self.frame_3, 18, 0, 1, 1)
        self.trainIntro1 = QtGui.QPushButton(self.dockWidgetContents_8)
        self.trainIntro1.setObjectName(_fromUtf8("trainIntro1"))
        self.gridLayout_2.addWidget(self.trainIntro1, 5, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 15, 0, 1, 1)
        self.frame_2 = QtGui.QFrame(self.dockWidgetContents_8)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayoutWidget = QtGui.QWidget(self.frame_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 371, 128))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.buttonPage10 = QtGui.QPushButton(self.gridLayoutWidget)
        self.buttonPage10.setObjectName(_fromUtf8("buttonPage10"))
        self.gridLayout.addWidget(self.buttonPage10, 1, 0, 1, 1)
        self.buttonPage18 = QtGui.QPushButton(self.gridLayoutWidget)
        self.buttonPage18.setObjectName(_fromUtf8("buttonPage18"))
        self.gridLayout.addWidget(self.buttonPage18, 2, 0, 1, 1)
        self.buttonPage14 = QtGui.QPushButton(self.gridLayoutWidget)
        self.buttonPage14.setObjectName(_fromUtf8("buttonPage14"))
        self.gridLayout.addWidget(self.buttonPage14, 1, 1, 1, 1)
        self.buttonPage3 = QtGui.QPushButton(self.gridLayoutWidget)
        self.buttonPage3.setObjectName(_fromUtf8("buttonPage3"))
        self.gridLayout.addWidget(self.buttonPage3, 0, 0, 1, 1)
        self.buttonPage6 = QtGui.QPushButton(self.gridLayoutWidget)
        self.buttonPage6.setObjectName(_fromUtf8("buttonPage6"))
        self.gridLayout.addWidget(self.buttonPage6, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.frame_2, 16, 1, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.dockWidgetContents_8)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_2.addWidget(self.pushButton_2, 1, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 17, 1, 1, 1)
        self.responseButton1 = QtGui.QPushButton(self.dockWidgetContents_8)
        self.responseButton1.setObjectName(_fromUtf8("responseButton1"))
        self.gridLayout_2.addWidget(self.responseButton1, 7, 1, 1, 1)
        self.responseButton3 = QtGui.QPushButton(self.dockWidgetContents_8)
        self.responseButton3.setObjectName(_fromUtf8("responseButton3"))
        self.gridLayout_2.addWidget(self.responseButton3, 11, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 15, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.dockWidgetContents_8)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 3, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.dockWidgetContents_8)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.dockWidgetContents_8)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 4, 1, 1, 1)
        self.stimuActionOneButton = QtGui.QPushButton(self.dockWidgetContents_8)
        self.stimuActionOneButton.setObjectName(_fromUtf8("stimuActionOneButton"))
        self.gridLayout_2.addWidget(self.stimuActionOneButton, 7, 0, 1, 1)
        self.pushButton = QtGui.QPushButton(self.dockWidgetContents_8)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_2.addWidget(self.pushButton, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.dockWidgetContents_8)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 3, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 17, 0, 1, 1)
        self.responseButton2 = QtGui.QPushButton(self.dockWidgetContents_8)
        self.responseButton2.setObjectName(_fromUtf8("responseButton2"))
        self.gridLayout_2.addWidget(self.responseButton2, 9, 1, 1, 1)
        self.responseButton4 = QtGui.QPushButton(self.dockWidgetContents_8)
        self.responseButton4.setObjectName(_fromUtf8("responseButton4"))
        self.gridLayout_2.addWidget(self.responseButton4, 12, 1, 1, 1)
        self.stimuTwoFeedback = QtGui.QPushButton(self.dockWidgetContents_8)
        self.stimuTwoFeedback.setObjectName(_fromUtf8("stimuTwoFeedback"))
        self.gridLayout_2.addWidget(self.stimuTwoFeedback, 12, 0, 1, 1)
        self.stimuOneFeedback = QtGui.QPushButton(self.dockWidgetContents_8)
        self.stimuOneFeedback.setObjectName(_fromUtf8("stimuOneFeedback"))
        self.gridLayout_2.addWidget(self.stimuOneFeedback, 11, 0, 1, 1)
        self.frame = QtGui.QFrame(self.dockWidgetContents_8)
        self.frame.setMinimumSize(QtCore.QSize(0, 130))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.playButton = QtGui.QRadioButton(self.frame)
        self.playButton.setGeometry(QtCore.QRect(20, 30, 111, 22))
        self.playButton.setObjectName(_fromUtf8("playButton"))
        self.playButton2 = QtGui.QRadioButton(self.frame)
        self.playButton2.setGeometry(QtCore.QRect(20, 50, 116, 22))
        self.playButton2.setObjectName(_fromUtf8("playButton2"))
        self.playButton4 = QtGui.QRadioButton(self.frame)
        self.playButton4.setGeometry(QtCore.QRect(20, 90, 116, 22))
        self.playButton4.setObjectName(_fromUtf8("playButton4"))
        self.playButton3 = QtGui.QRadioButton(self.frame)
        self.playButton3.setGeometry(QtCore.QRect(20, 70, 116, 22))
        self.playButton3.setObjectName(_fromUtf8("playButton3"))
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(30, 10, 131, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(170, 50, 31, 17))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.radioButton_5 = QtGui.QRadioButton(self.frame)
        self.radioButton_5.setGeometry(QtCore.QRect(240, 50, 116, 22))
        self.radioButton_5.setObjectName(_fromUtf8("radioButton_5"))
        self.playButton5 = QtGui.QRadioButton(self.frame)
        self.playButton5.setGeometry(QtCore.QRect(20, 110, 116, 22))
        self.playButton5.setObjectName(_fromUtf8("playButton5"))
        self.playPushButton = QtGui.QPushButton(self.frame)
        self.playPushButton.setGeometry(QtCore.QRect(220, 90, 98, 27))
        self.playPushButton.setObjectName(_fromUtf8("playPushButton"))
        self.gridLayout_2.addWidget(self.frame, 16, 0, 1, 1)
        self.stimuActionTwoButton = QtGui.QPushButton(self.dockWidgetContents_8)
        self.stimuActionTwoButton.setObjectName(_fromUtf8("stimuActionTwoButton"))
        self.gridLayout_2.addWidget(self.stimuActionTwoButton, 9, 0, 1, 1)
        self.frame_4 = QtGui.QFrame(self.dockWidgetContents_8)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.textEdit = QtGui.QTextEdit(self.frame_4)
        self.textEdit.setGeometry(QtCore.QRect(30, 110, 151, 31))
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.coverButton3_2 = QtGui.QPushButton(self.frame_4)
        self.coverButton3_2.setGeometry(QtCore.QRect(200, 110, 98, 27))
        self.coverButton3_2.setObjectName(_fromUtf8("coverButton3_2"))
        self.gridLayout_2.addWidget(self.frame_4, 18, 1, 1, 1)
        self.trainIntro4 = QtGui.QPushButton(self.dockWidgetContents_8)
        self.trainIntro4.setObjectName(_fromUtf8("trainIntro4"))
        self.gridLayout_2.addWidget(self.trainIntro4, 6, 1, 1, 1)
        self.trainIntro3 = QtGui.QPushButton(self.dockWidgetContents_8)
        self.trainIntro3.setObjectName(_fromUtf8("trainIntro3"))
        self.gridLayout_2.addWidget(self.trainIntro3, 6, 0, 1, 1)
        self.trainIntro2 = QtGui.QPushButton(self.dockWidgetContents_8)
        self.trainIntro2.setObjectName(_fromUtf8("trainIntro2"))
        self.gridLayout_2.addWidget(self.trainIntro2, 5, 1, 1, 1)
        self.trainIntroAgain = QtGui.QPushButton(self.dockWidgetContents_8)
        self.trainIntroAgain.setObjectName(_fromUtf8("trainIntroAgain"))
        self.gridLayout_2.addWidget(self.trainIntroAgain, 13, 0, 1, 1)
        self.dockWidget_3.setWidget(self.dockWidgetContents_8)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget_3)
        self.actionOpen = QtGui.QAction(MainWindow)
        self.actionOpen.setObjectName(_fromUtf8("actionOpen"))
        self.menuOpen.addAction(self.actionOpen)
        self.menubar.addAction(self.menuOpen.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Wizard", None))
        self.menuOpen.setTitle(_translate("MainWindow", "File", None))
        self.coverButton1.setText(_translate("MainWindow", "I think it is a nice day today !", None))
        self.coverButton2.setText(_translate("MainWindow", "About LEGO, more than 400 billion Lego bricks have been produced since 1958. Can you believe it?", None))
        self.coverButton3.setText(_translate("MainWindow", "Since we are playing with LEGO, did you know that LEGO is very very popular amongst adults population", None))
        self.coverButton4.setText(_translate("MainWindow", "I love LEGO !", None))
        self.coverButton5.setText(_translate("MainWindow", "Its going to be sunny tomorrow, I love it.", None))
        self.coverButton6.setText(_translate("MainWindow", "I don\'t like rain, even though I don\'t go outside.", None))
        self.trainIntro1.setText(_translate("MainWindow", "Hello, nice to meet you. ", None))
        self.buttonPage10.setText(_translate("MainWindow", "Page 10", None))
        self.buttonPage18.setText(_translate("MainWindow", "Page 18", None))
        self.buttonPage14.setText(_translate("MainWindow", "Page 14", None))
        self.buttonPage3.setText(_translate("MainWindow", "Page 3", None))
        self.buttonPage6.setText(_translate("MainWindow", "Page 6", None))
        self.pushButton_2.setText(_translate("MainWindow", "Turn Off", None))
        self.responseButton1.setText(_translate("MainWindow", "Menuel Response One", None))
        self.responseButton3.setText(_translate("MainWindow", "Menuel Response Three", None))
        self.label_2.setText(_translate("MainWindow", "0", None))
        self.label_3.setText(_translate("MainWindow", "Current time:", None))
        self.label_4.setText(_translate("MainWindow", "0", None))
        self.stimuActionOneButton.setText(_translate("MainWindow", "Screen Training (Sound and Button)", None))
        self.pushButton.setText(_translate("MainWindow", "Next Action", None))
        self.label.setText(_translate("MainWindow", "No. Action:", None))
        self.responseButton2.setText(_translate("MainWindow", "Menuel Response Two", None))
        self.responseButton4.setText(_translate("MainWindow", "Menuel Response Four", None))
        self.stimuTwoFeedback.setText(_translate("MainWindow", "Powerhand Training", None))
        self.stimuOneFeedback.setText(_translate("MainWindow", "Screen Training (Speech and Button)", None))
        self.playButton.setText(_translate("MainWindow", "Of course !", None))
        self.playButton2.setText(_translate("MainWindow", "Yes I can !", None))
        self.playButton4.setText(_translate("MainWindow", "Don\'t worry. ", None))
        self.playButton3.setText(_translate("MainWindow", "No problem !", None))
        self.label_5.setText(_translate("MainWindow", "Choose a phrase", None))
        self.label_6.setText(_translate("MainWindow", "or", None))
        self.radioButton_5.setText(_translate("MainWindow", "random", None))
        self.playButton5.setText(_translate("MainWindow", "Nothing", None))
        self.playPushButton.setText(_translate("MainWindow", "No Problem !", None))
        self.stimuActionTwoButton.setText(_translate("MainWindow", "Highfive Training", None))
        self.coverButton3_2.setText(_translate("MainWindow", "PlayText", None))
        self.trainIntro4.setText(_translate("MainWindow", "Some of my interactions are like this:", None))
        self.trainIntro3.setText(_translate("MainWindow", "I will help you sometimes, and sometimes I need your help and encouragement.  ", None))
        self.trainIntro2.setText(_translate("MainWindow", "Today we are going to work together to finish a task.", None))
        self.trainIntroAgain.setText(_translate("MainWindow", "Would you like to try the actions again? ", None))
        self.actionOpen.setText(_translate("MainWindow", "Open", None))

